version: '3'
services:
  postgresql:
    image: postgres:15.1
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: AwesomePassword1234
      POSTGRES_USER: grimoirebots
      POSTGRES_DB: grimoirebots
      # https://docs.djangoproject.com/en/stable/ref/databases/#optimizing-postgresql-s-configuration
      PGCLIENTENCODING: UTF8
      TZ: UTC
    # https://github.com/docker-library/docs/blob/master/postgres/README.md#caveats
    shm_size: 256m
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - grimoirebots

volumes:
  postgresql-data:
    name: postgresql-data

networks:
  grimoirebots:
    name: grimoirebots
